# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master
  

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  GO111MODULE: 'on'
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  Version.MajorMinor: 0.0
  Version.Revision: $[counter(variables['Version.MajorMinor'], 0)]

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
  displayName: 'Set up the Go workspace'

- script: |
    go version
    go mod download
    go build -o $(Build.ArtifactStagingDirectory)/terraform-provider-opendistro
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, then build'


- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github-con'
    repositoryName: 'SvenHamers/terraform-opendistro-security'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v0.0.1'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'



